In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

STEP 1 Data Collection

In [8]:
pd.read_excel("/content/hospital_patient_treatment_dataset.xlsx")

,Department,Average of Treatment Cost,Unnamed: 2,Unnamed: 3
0,Cardiology,75039.257500,NaN,NaN
1,Gastroenterology,72489.531220,NaN,TallerBar= Higher Cost
2,Neurology,75960.437857,NaN,NaN
3,Oncology,89613.507097,NaN,NaN
4,Orthopedics,89613.622105,NaN,NaN
5,Pediatrics,75170.029474,NaN,NaN
6,Grand Total,79698.513500,NaN,NaN

In [10]:
df.head()

,Patient ID,Department,Treatment Type,Doctor Name,Gender,Age,Treatment Cost,Hospital Stay (Days),Recovery Score,Cost Per Day,Cost Efficiency Score
0,P1001,Gastroenterology,Therapy,Dr. L. Khan,Female,12,68632.97,21,82,3268.236667,836.987439
1,P1002,Pediatrics,Medication,Dr. M. Patel,Male,52,10231.42,20,42,511.571000,243.605238
2,P1003,Pediatrics,Therapy,Dr. L. Khan,Male,79,10160.24,2,72,5080.120000,141.114444
3,P1004,Pediatrics,Therapy,Dr. L. Khan,Female,23,103508.96,20,50,5175.448000,2070.179200
4,P1005,Orthopedics,Medication,Dr. T. Mehta,Female,7,143427.52,6,43,23904.586667,3335.523721

In [12]:
df.shape

(200, 11)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient ID             200 non-null    object
 1   Department             200 non-null    object
 2   Treatment Type         200 non-null    object
 3   Doctor Name            200 non-null    object
 4   Gender                 200 non-null    object
 5   Age                    200 non-null    int64
 6   Treatment Cost         200 non-null    float64
 7   Hospital Stay (Days)   200 non-null    int64
 8   Recovery Score         200 non-null    int64
 9   Cost Per Day           200 non-null    float64
 10  Cost Efficiency Score  200 non-null    float64
dtypes: float64(3), int64(3), object(5)
memory usage: 17.3+ KB

STEP 2 Data Cleaning & Preprocessing

In [14]:
df.isnull().sum()

Patient ID               0
Department               0
Treatment Type           0
Doctor Name              0
Gender                   0
Age                      0
Treatment Cost           0
Hospital Stay (Days)     0
Recovery Score           0
Cost Per Day             0
Cost Efficiency Score    0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.dtypes

Patient ID                object
Department                object
Treatment Type            object
Doctor Name               object
Gender                    object
Age                        int64
Treatment Cost           float64
Hospital Stay (Days)       int64
Recovery Score             int64
Cost Per Day             float64
Cost Efficiency Score    float64
dtype: object

In [25]:
df["calculated_cost_per_day"]=df["Treatment Cost"]/df["Hospital Stay (Days)"]

In [30]:
df[["Cost Per Day", "calculated_cost_per_day"]].head()

   Cost Per Day  calculated_cost_per_day
0   3268.236667              3268.236667
1    511.571000               511.571000
2   5080.120000              5080.120000
3   5175.448000              5175.448000
4  23904.586667             23904.586667

In [36]:
df[["Treatment Cost", "Hospital Stay (Days)", "Cost Per Day"]].describe()

       Treatment Cost  Hospital Stay (Days)   Cost Per Day
count      200.000000            200.000000     200.000000
mean     79698.513500             16.015000   10035.431556
std      43406.740591              9.109318   17292.321772
min       5444.800000              1.000000     276.102000
25%      45451.882500              7.000000    3055.217187
50%      79268.870000             17.000000    4996.367946
75%     118701.897500             24.000000   10083.238864
max     149340.160000             30.000000  143381.070000

In [37]:
df.shape

(200, 12)

STEP 3 Exploratory Data Analysis

Basic Dataset Overview

In [38]:
df.describe()

,Age,Treatment Cost,Hospital Stay (Days),Recovery Score,Cost Per Day,Cost Efficiency Score,calculated_cost_per_day
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,41.710000,79698.513500,16.015000,70.375000,10035.431556,1197.805497,10035.431556
std,26.136978,43406.740591,9.109318,17.726407,17292.321772,738.076745,17292.321772
min,1.000000,5444.800000,1.000000,40.000000,276.102000,58.126737,276.102000
25%,19.000000,45451.882500,7.000000,55.000000,3055.217187,631.300164,3055.217187
50%,40.000000,79268.870000,17.000000,72.000000,4996.367946,1154.388484,4996.367946
75%,62.250000,118701.897500,24.000000,85.000000,10083.238864,1617.130753,10083.238864
max,90.000000,149340.160000,30.000000,100.000000,143381.070000,3567.126585,143381.070000

Patient Demographics Analysis

In [41]:
df["Age"].describe()

count    200.000000
mean      41.710000
std       26.136978
min        1.000000
25%       19.000000
50%       40.000000
75%       62.250000
max       90.000000
Name: Age, dtype: float64

Department Wise Analysis

In [43]:
dept_summary = df.groupby("Department").agg({
    "Treatment Cost": "mean",
    "Hospital Stay (Days)": "mean",
    "Recovery Score": "mean"
}).round(2)

dept_summary

                  Treatment Cost  Hospital Stay (Days)  Recovery Score
Department
Cardiology              75039.26                 15.83           70.50
Gastroenterology        72489.53                 15.61           71.80
Neurology               75960.44                 15.18           66.39
Oncology                89613.51                 16.94           72.42
Orthopedics             89613.62                 15.63           67.26
Pediatrics              75170.03                 16.82           73.13

Treatment Type Analysis

In [44]:
treatment_summary = df.groupby("Treatment Type").agg({
    "Treatment Cost": "mean",
    "Hospital Stay (Days)": "mean",
    "Recovery Score": "mean",
    "Cost Efficiency Score": "mean"
}).round(2)

treatment_summary

,Treatment Cost,Hospital Stay (Days),Recovery Score,Cost Efficiency Score
Treatment Type,,,,
Medication,80753.25,15.44,67.58,1263.89
Observation,78660.43,16.51,70.02,1155.82
Surgery,83729.88,15.21,73.29,1243.65
Therapy,75643.99,16.96,70.98,1120.57

Cost VS Outcome Relationship

In [45]:
df[["Treatment Cost", "Recovery Score"]].corr()

                Treatment Cost  Recovery Score
Treatment Cost        1.000000        0.088918
Recovery Score        0.088918        1.000000

Hospital Stay Impact on Cost

In [47]:
df[["Hospital Stay (Days)", "Treatment Cost"]].corr()

                      Hospital Stay (Days)  Treatment Cost
Hospital Stay (Days)               1.00000         0.07626
Treatment Cost                     0.07626         1.00000

Cost Efficiency Evaluation

In [48]:
df.sort_values(
    by="Cost Efficiency Score",
    ascending=False
).head(5)

,Patient ID,Department,Treatment Type,Doctor Name,Gender,Age,Treatment Cost,Hospital Stay (Days),Recovery Score,Cost Per Day,Cost Efficiency Score,calculated_cost_per_day
5,P1006,Cardiology,Medication,Dr. A. Sharma,Female,78,146252.19,9,41,16250.243333,3567.126585,16250.243333
160,P1161,Pediatrics,Therapy,Dr. A. Sharma,Male,80,140818.37,9,42,15646.485556,3352.818333,15646.485556
4,P1005,Orthopedics,Medication,Dr. T. Mehta,Female,7,143427.52,6,43,23904.586667,3335.523721,23904.586667
92,P1093,Oncology,Observation,Dr. T. Mehta,Other,1,146289.27,17,47,8605.251176,3112.537660,8605.251176
43,P1044,Pediatrics,Observation,Dr. T. Mehta,Male,62,149340.16,18,49,8296.675556,3047.758367,8296.675556

STEP 4 KPI Identification & Calculation